            - nom: Cache
  utilisations: actions/cache@v5.0.1
  avec:
    # Une liste de fichiers, répertoires et modèles génériques à mettre en cache et restaurer
    chemin: 
    # Une clé explicite pour restaurer et enregistrer le cache
    clé: 
    # Une chaîne multiligne ordonnée répertoriant les clés appariées au préfixe, qui sont utilisées pour restaurer le cache obsolète si aucun coup de cache ne s'est produit pour la clé. Remarque `cache-hit` retourne faux dans ce cas.
    Restauration-clés: # optionnel
    # La taille du morceau utilisée pour diviser les fichiers volumineux pendant le téléchargement, en octets
    upload-chunk-size: # optionnel
    # Un booléen optionnel lorsqu'il est activé, permet aux coureurs Windows d'enregistrer ou de restaurer des caches qui peuvent être restaurés ou enregistrés respectivement sur d'autres plates-formes
    enableCrossOsArchive: # optionnel, par défaut est false
    # Échouer le flux de travail si l'entrée de cache n'est pas trouvée
    fail-on-cache-miss: # optionnel, default est false
    # Vérifiez si une entrée de cache existe pour l'entrée (s) donnée (clé, restauration-keys) sans télécharger le cache
    recherche-seulement: # optionnel, par défaut est false
    # Exécutez l'étape de publication pour enregistrer le cache même si une autre étape avant d'échouer
    save-always: # optionnel, par défaut est false
          
